### ISSUE TITLE
How to upload images on AWS S3?

### ISSUE THREAD

**Issue by jigneshchudasama05** [FutoRicky/ember-cli-dropzonejs#31]
I am using ember js for front-end and laravel 5 for back end

**Comment by denisbetsi** [comment]
You'll have to create a script to receive multipart/form-data and create temporary file, then use S3 SDK, to putObject into bucket. I don't think you can directly upload, because S3 creates signed URL, I am not sure it'll allow upload of multiple files per signed URL, and from what I see, this component has 1 Upload URL.

**Comment by denisbetsi** [comment]
Also check out
https://maxoffsky.com/code-blog/howto-ajax-multiple-file-upload-in-laravel/

**Comment by FutoRicky** [comment]
Also, checkout https://github.com/FutoRicky/ember-cli-dropzonejs/issues/39
